### ISSUE TITLE
我是从携程的appt过来的

### ISSUE THREAD

**Issue by Dongzzzz** [BaoBaoJianqiang/AAPT#1]
你这里的那个携程aapt的分支 你编译过了么？ 有什么问题没有？
你这个携程aapt的分支 和 携程自己的那个aapt代码有什么区别么？ @BaoBaoJianqiang

**Comment by BaoBaoJianqiang** [comment]
是一样的。你比较master和携程分支的差异，就能知道修改了哪些。有些是携程自己特殊的逻辑。

**Comment by BaoBaoJianqiang** [comment]
老弟加个微信聊聊？同道中人嘛

**Comment by Dongzzzz** [comment]
恩 我微信号 AoLoTo
